### PR TITLE
Y3

### PR DESCRIPTION
**Pull request by ferdianjovan**
Hi Lars,
I am adding vision_people_logging stuff, so that the PerceptionPeople will capture a snapshot of UBD information which later on will be an input for world modelling/observation. Otherwise, no topic will feed data to world modelling.
I also add vision_people_logging launch file to be run from object_search.launch.

### CODE REVIEW

**Comment by hawesie** [comment]
Is this ok to merge? @kunzel

**Comment by hawesie** [comment]
@kunzel I don't have permission to do this, but we need it on the robot...

**Comment by kunzel** [comment]
@ferdianjovan have you tested this PR successfully on the robot?

**Comment by ferdianjovan** [comment]
I tested this on Bob and worked fine.

**Pull request merged**
